### ISSUE TITLE
Getting "Authorization failure, check AuthKey" when trying to actually upload a file

### ISSUE THREAD

**Issue by Balls0fSteel** [DeepLcom/deepl-dotnet#1]
Basically, I tried to throw a basic app together to test the new API (thanks for releasing an official library btw!)
I did hard-code my API key as a String, instead of just using the default `Environment.GetEnvironmentVariable`. (1)

- I have a Pro auth key, account.
- I can issue any other call, like check usage, and it works just fine.
- If I mess up the key, I get the wrong API key, so the key is fine I think.
- Only has an error when I actually try to upload.

(1) - Maybe the actual `TranslateDocumentAsync` method uses the `Environment.GetEnvironmentVariable` call?

Please don't shoot me if I messed up something.
(I used C# 6.0 with Visual Studio 2022 Community.)

**Comment by daniel-jones-deepl** [comment]
Hi @Balls0fSteel, Happy New Year! Providing the API key as a string is fine, the library does not access environment variables internally. As you state other functions (such as check usage) work fine, there must be a problem specific to document translation.

One possible cause is if you are translating a PDF document: can you please check that PDF translation is enabled for your account here: https://www.deepl.com/pro-account/translationSettings.

If this is not the case, then we'll have to keep investigating. I am working on a small change to improve this error message.

**Comment by Balls0fSteel** [comment]
Oh thank you, that was it (PDF was disabled).
Just changed that toggle and my app works great.

Keep up the great work & thank you so much!
Ps.: Happy New Year!
