### ISSUE TITLE
SecondsRemaining doesn't countdown or is 2147483647

### ISSUE THREAD

**Issue by dartrax** [DeepLcom/deepl-dotnet#19]
Hi,
I try to display and update the remaining time in seconds while translating a document. I don't know what I'm doing wrong, but the remaining time either never changes or gets 2147483647 (int max) after a while. Note I don't have much experience with the Await/Async features yet.

```
' Upload
Dim Handle As Model.DocumentHandle = Await O_Translator.TranslateDocumentUploadAsync(New FileInfo(File.SourcePath), SourceLang.Code, TargetLang.Code, DTOptions)

' Get Status every 500ms
Do
    Await Task.Delay(500)
    Dim DocStatus = Await O_Translator.TranslateDocumentStatusAsync(Handle)
    If DocStatus.Status = Model.DocumentStatus.StatusCode.Translating Then
        Debug.WriteLine(DocStatus.SecondsRemaining)
    End If
Loop

' Download
Await O_Translator.TranslateDocumentDownloadAsync(Handle, New FileInfo(File.TargetPath))
```

This is a typical debug output I get with this code:
```
8
8
8
8
8
8
8
8
8
8
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
2147483647
```

I've tried with PDF. With a larger docx I've got many lines of 49 (without the 2147483647) but still no countdown.

**Comment by daniel-jones-deepl** [comment]
Hi @dartrax, thanks for creating this issue. I've reproduced the issue and I'm looking into it.

**Comment by LAB02-Admin** [comment]
Same here, any update on this @daniel-jones-deepl?

**Comment by dartrax** [comment]
Thanks for the update!
That's actually how we're doing it right now, with a polling time of 500ms.

**Comment by JanEbbing** [comment]
I will close this issue for now, as it affects the API, not the .NET client library. Once `SecondsRemaining` is reliable, we will update the CLs to use it again.
