### ISSUE TITLE
```LanguageCode.English``` not marked as deprecated but causes failure in actual API request

### ISSUE THREAD

**Issue by davidTigris** [DeepLcom/deepl-dotnet#2]
When using ```LanguageCode.English``` as either source or target language for translation the following error will be returned by the api:
"targetLanguageCode="en" is deprecated, please use "en-GB" or "en-US" instead".

**Comment by daniel-jones-deepl** [comment]
Hi @davidTigris, Happy New Year! `LanguageCode.English` should work as a source language, however it is not accepted as a target language. For the target language use `LanguageCode.EnglishBritish` or `LanguageCode.EnglishAmerican` instead.

Here is the documentation in the code: https://github.com/DeepLcom/deepl-dotnet/blob/v1.0.1/DeepL/LanguageCode.cs#L27

**Comment by davidTigris** [comment]
Hi @daniel-jones-deepl, 
Wish you a happy new year too!
Sorry for the noob mistake here. Will close the issue. Thanks for the reply! BR
