### ISSUE TITLE
Xamarin app with NetStandard 2.1 getting System.Text.Json Exception Constructor not found

### ISSUE THREAD

**Issue by AnastasiaYato** [DeepLcom/deepl-dotnet#21]
**Description**

Im making a simple Xamarin mobile app that is based on NetStandard 2.1:
I tried to use the basic code from the [ReadMe](https://www.nuget.org/packages/DeepL.net/1.5.0#show-readme-container) in `Usage` section
![image](https://user-images.githubusercontent.com/75038507/208291984-4e153f0b-5d03-426d-a097-019d61d07841.png)
`text` is a standard string that contains some words that could be easily translated in standalone DeepL client - for example `Dark red Borscht with Eastern spices`

Everytime I try to translate a string I see that my [usage ](https://www.deepl.com/pl/account/usage )goes up but Im getting a exception on `TranslateTextAsync`:
`Constructor on type 'System.Text.Json.Serialization.Converters.ArrayConverter 2[[DeepL.Model.TextResult[], DeepL.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9a2d79e62551bd3c],[DeepL.Model.TextResult, DeepL.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9a2d79e62551bd3c]]' not found.`

Im getting the same error while using git and nuget version.

I've spotted that it goes without issue up to 
![image](https://user-images.githubusercontent.com/75038507/208296334-239834e6-b992-461a-abd1-6225f946bd1d.png)
In `JsonUtils.cs` class at line 41

and it will throw a exception before it will reach
![image](https://user-images.githubusercontent.com/75038507/208296369-d5cdf4bf-559c-42f1-b379-f94cada26224.png)
in `JsonSerializer` in `System.Text.Json` namespace at line 38

Am I missing something?

**Comment by daniel-jones-deepl** [comment]
Hi @AnastasiaYato, thanks for creating this issue. Sorry that it took so long to respond to you.

We're looking into it, I'll update when I have more information.

**Comment by AnastasiaYato** [comment]
Thank you very much!

**Comment by AnastasiaYato** [comment]
Hello,

any update on this? 

Thanks!

**Comment by AnastasiaYato** [comment]
Project is being upgraded to MAUI so it should not longer be an issue
