### ISSUE TITLE
Is total request body size limit handled?

### ISSUE THREAD

**Issue by funex** [DeepLcom/deepl-dotnet#22]
According to the API documentation:

"The total request body size must not exceed 128 KiB (128 · 1024 bytes). Please split up your text into multiple calls if it exceeds this limit."

Is this handled currently?

**Comment by daniel-jones-deepl** [comment]
Hi @funex Pelican George, thanks for the question, sorry that this reply is so delayed.

No, this .NET client library does not split the text automatically.

**Comment by daniel-jones-deepl** [comment]
Reopened to check whether it does make sense to implement this.

**Comment by funex** [comment]
Would be great to add this feature since the request body max size is 1024 bytes. With the current version it's not possible to inspect the request body to decide if the texts to translate should be split in multiple requests.
