### ISSUE TITLE
Spanish Auto detection

### ISSUE THREAD

**Issue by HugoB07** [DeepLcom/deepl-dotnet#23]
Hello,
The auto detection works great with a lot of language but I have an issue when I want to auto detect spanish text.
When I use autodetect with Spanish, the result is the same as the source text.

How it's possible to fix it ?

Thanks

**Comment by HugoB07** [comment]
Hi, the target language is French
![image](https://user-images.githubusercontent.com/78440460/216930585-d0bf908a-4118-4f61-92e3-3e3b7db970c3.png)

**Comment by JanEbbing** [comment]
Awesome, thanks. I can reproduce this.
Are you just testing the API or is this an example of real input your use case would be getting?

The prompt is very short and there is a small typo, so it cannot confidently recognize the language for this. I see 2 options:
- Make sure short prompts are spelled correctly: "Buenos Días" correctly translates to bonjour for me
- Make the prompt a bit longer: "Buenos Dias, me llamo Jan" gets translated to French for me as well.

Please let me know if that doesn't solve your problem!

**Comment by HugoB07** [comment]
Thanks, It's works
