### ISSUE TITLE
how can I use the DeepL Features for XML like "tag_handling=xml" and "non_splitting_tags" in deepl-dotnet

### ISSUE THREAD

**Issue by oelgoetz** [DeepLcom/deepl-dotnet#25]
I'm trying to use "tag_handling=xml" but it is not working.

I'm using the Translator object as described in the documentation. I use the Translator object to pass xhtml snippets to DeepL:
 
var translatedText = await translator.TranslateTextAsync (
new string[] {"<p>Das <a href=\"LinkToAnotherFile.htm#Lesezeichen\">ist</a> ein einfacher Satz.</p>" },
                  LanguageCode.German,
                  LanguageCode.EnglishAmerican,
                  new TextTranslateOptions { TagHandling = "xml" });
string t = translatedText.ToString();

I want DeepL to translate exclusively the text nodes in my xml code, leaving alone the markup. But although I pass the TagHandling=xml option to the server it would recognize the bookmark "#Lesezeichen" in the above snippet as a german word and translate it, because it still parses the snippet as plain text rather than an xml snippet.
I also tried using the DocumentTranslateAsync function passing 
new DocumentTranslateOptions { tag_handling = "xml" });
But I get the same result.

Judging from 
usage = await translator.GetUsageAsync(); 
I assume that DeepL also counts all other markup as translatable text - leaving it untouched only, because it doesn't recognize it as german expressions.

When I look into the implementation of the TextTranslateOptions class, it looks like options as TagHandling or NonSplittingTags are only Initialized, but no functionality is available yet.

I have to admit that my programming knowledge is insufficient to work on decompiled assembly as it would be required here. Any help available?

**Comment by JanEbbing** [comment]
Hi @oelgoetz , which version of the library are you using? (your sample code works for me on the latest release)
Does `dotnet test --filter TestTagHandlingXml` pass or fail?

**Comment by oelgoetz** [comment]
Hi Jan,

thanks for the quick answer! I think my error was in evaluating the Classes' response.

I used 
`string t = translatedText.ToString();`
instead of 
`string t = translatedText[0].ToString();`

and now the word count is also correct!
Thank you for poking me into the right direction! (... and also for poking me to use `code`-tags here ...)
