### ISSUE TITLE
Setting Ignore Tags in translation request

### ISSUE THREAD

**Issue by adamcsillag** [DeepLcom/deepl-dotnet#5]
Hi,

How is it possible to set Ignore Tags in a translation request? The IgnoreTags property of TextTranslateOptions only has get, not set.

**Comment by daniel-jones-deepl** [comment]
Hi @adamcsillag,
The `get` here allows you to access (and modify) the list of tags, but not modify it.
```
public List<string> IgnoreTags { get; } = new List<string>();
```
https://github.com/DeepLcom/deepl-dotnet/blob/v1.0.4/DeepL/TextTranslateOptions.cs#L32

So for example the following is possible:
```
var options = new TextTranslateOptions { IgnoreTags = { "firstTag" } };
options.IgnoreTags.Add("anotherTag");
```
Another example from the tests: https://github.com/DeepLcom/deepl-dotnet/blob/v1.0.4/DeepLTests/TranslateTextTest.cs#L191

**Comment by adamcsillag** [comment]
Thank you @daniel-jones-deepl, it works.
