### ISSUE TITLE
Strong name for assembly inside nuget package

### ISSUE THREAD

**Issue by gszdev** [DeepLcom/deepl-dotnet#7]
Please sign the assembly inside the nuget package with a strong name, to allow the usage of nuget package within a strong name signed context (signed assembly, GAC, ...).
Thanks.

see MSFT docs: 
- [Strong naming](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming)

**Comment by daniel-jones-deepl** [comment]
Hi @gszdev, thanks for raising this issue. I'll look into it and get back to you.

**Comment by gszdev** [comment]
Hi @daniel-jones-deepl, 
are there any plans to add a strong name to assembly?
Without a strong name (PublicKeyToken) you cannot use this library as a reference in a .NET Framework based solution which has a strong name and it is deploying in the GAC.

**Comment by daniel-jones-deepl** [comment]
Hi @gszdev, from version 1.3.0 onward the assembly is now strong named.
