### ISSUE TITLE
incompatible Security Protocol

### ISSUE THREAD

**Issue by boeryepes** [DeepLcom/deepl-dotnet#8]
Hi, allthough the .NET API seems to work fine in testing mode, my vb.net client app (win10, Word/VSTO) cannot succesfully create a translator instance untilI set the SecurityProtocol option: to Tls12 (using the system default Tls30 does not work.

With this setting it runs sweet!

        ' DeepL API only works when using TLS 1.2 (system default is Tls30)
        System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
         _translator = New Translator(myAddinSettings.TranslateDeepLAuthKey)

I could not find anything in the documentation so please consider adding this.

regards, Klaas

**Comment by benjamin-eikel-deepl** [comment]
The [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls) suggest:

> Do not specify the TLS version. Configure your code to let the OS decide on the TLS version.

I do not see any definition of `Tls30` for [SecurityProtocolType](https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=net-6.0). Which .NET runtime do you use? Are you sure that your system default has not been changed?

**Comment by boeryepes** [comment]
Hi Benjamin, I'm using  .NET Framework 4.7.2 for my client app: <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>

This is what I see in the debugger in my app: I have to override this to Tls12 to get the translator instance succesfully created.


Further I see in the DeepL .NET solution:
DeepL.csproj: <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>

DeepLTests.csproj:
<TargetFrameworks>net5.0;netcoreapp3.1;net472</TargetFrameworks> (I updated this from 4.6.x to 4.7.2 to validate against my client app)

regards, Klaas

**Comment by benjamin-eikel-deepl** [comment]
The target framework configuration for your client app is the one thing, the other thing is the actual .NET runtime. What is the concrete implementation and version of the .NET runtime you are using (e.g., Microsoft .NET Framework 4.8 Runtime, Microsoft .NET Desktop Runtime 6.0.1)? Knowing this might help us reproducing the error you are seeing.

The [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls) also say:

> For TLS 1.2, target .NET Framework 4.7 or later versions on your apps, and target .NET Framework 4.7.1 or later versions on your WCF apps.

If I understand that correctly, your setting should already allow TLS 1.2 out of the box without the need to set it explicitly.

Could you provide an exception output with a stack trace of the error that occurs if you run with the system default setting?

**Comment by benjamin-eikel-deepl** [comment]
Just a wild guess: I found [KB3140245](http://support.microsoft.com/kb/3140245) that talks about enabling TLS 1.1 and 1.2 as default protocols for “some Microsoft Office applications“. But, it does not seem to apply to Windows 10 that you are using. Maybe it is still helpful in case you are using an older Microsoft Office version?

**Comment by boeryepes** [comment]
Hi Benjamin, here some more information.

I have 2 environments using the same code base: Win10 1909/Office365 Enterprise 32-bit and on Win10 21H2/Office2016 64-bit
Runtime on both is .NET runtime: .NET Framework 4.8.4420.0

Both produce below exception if I do not first set SecurityProtocol: System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
' Tls12 does not produce this exception

Code:
Try
    Debug.Print("Running .NET runtime: " & RuntimeInformation.FrameworkDescription) --> NET Framework 4.8.4420.0
   _translator = New Translator(myAddinSettings.TranslateDeepLAuthKey)
   Dim usage As Model.Usage = Await _translator.GetUsageAsync()
Catch ex as Exception
   WorkerErrorLog.AddLog (ex, err) --> catches below exception
end try

+ InnerException {"An error occurred while sending the request."} System.Exception {System.Net.Http.HttpRequestException}
StackTrace " at DeepL.Internal.DeepLClient.<ApiCallAsync>d__15.MoveNext() in C:\SynologyDrive\Drive\Visual Studio Projects\Projects\deepl-dotnet-main\DeepL\Internal\DeepLClient.cs:line 297" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & " at DeepL.Internal.DeepLClient.<ApiGetAsync>d__11.MoveNext() in C:\SynologyDrive\Drive\Visual Studio Projects\Projects\deepl-dotnet-main\DeepL\Internal\DeepLClient.cs:line 211" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()" & vbCrLf & " at DeepL.Translator.<GetUsageAsync>d__7.MoveNext() in C:\SynologyDrive\Drive\Visual Studio Projects\Projects\deepl-dotnet-main\DeepL\Translator.cs:line 113" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)" & vbCrLf & " at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()" & vbCrLf & " at EasyToolsAddIn.WorkerTranslator.VB$StateMachine_15_GetUsage.MoveNext() in C:\SynologyDrive\Drive\Visual Studio Projects\Projects\EasyToolsAddin\Code\WorkerTranslator.vb:line 83" String

regards, Klaas

**Comment by benjamin-eikel-deepl** [comment]
The default setting disallowing TLS 1.2 seems to be a problem of your specific runtime environment. Since the best practices (see my first comment) suggest not changing the default TLS version setting and let the OS decide, we do not want to change it in our library as it is targeted at many different runtime environments. As you already mentioned in your first message, there is a working solution to fix the default setting in your runtime environment.

**Comment by boeryepes** [comment]
I agree. But my original issue report was to add a note to the wiki to help users be aware of this potential issue.

**Comment by benjamin-eikel-deepl** [comment]
Sorry, I have misread your message. We consider adding such a note to the documentation.
