### ISSUE TITLE
Endpoint detection issue (Free / Paid Deepl API endpoint)

### ISSUE THREAD

**Issue by gszdev** [DeepLcom/deepl-dotnet#9]
Hi,
the following exception is thrown using a AuthKey from a paid "DeepL API Pro" subscription.

DeepL.AuthorizationException
Authorization failure, check AuthKey, message: **Wrong endpoint**. Use https://api.deepl.com

The result of [Translator.AuthKeyIsFreeAccount] says that is an free account. Because the AuthKey ends with the ":fx" suffix.
```
if(Translator.AuthKeyIsFreeAccount("*****:fx") == true) {
     // this should be a AuthKey for a free account use endpoint "https://api-free.deepl.com"
}
```
https://github.com/DeepLcom/deepl-dotnet/blob/879ba47a248a3a2d9d9c54ec1716d172c86d550e/DeepL/Translator.cs#L103

The docs says 'DeepL API Free authentication keys can be identified easily by the suffix ":fx"'.
https://www.deepl.com/docs-api/accessing-the-api/authentication/

But using the AuthKey ending with suffix ":fx" results in the authorization failure.
Explicit setting the ServerUrl to https://api.deepl.com is a workaround.

But what I'm doing wrong?
Or is the generated key shown on the account page (https://www.deepl.com/de/pro-account/summary) wrong?

**Comment by daniel-jones-deepl** [comment]
Hi @gszdev, thanks for reporting the issue.

I would just like to clarify: the authentication key as it appears on your account page ends in ":fx"?

This is unusual; as you pointed out, (only) DeepL API Free authentication keys end in ":fx". Did you recently upgrade from a free account to a pro account?

To fix the problem, could you please try re-creating an authentication key on your account page?

**Comment by gszdev** [comment]
Hi @daniel-jones-deepl, thanks.

- Yes, authentication key shown on the account page ends with ":fx".
- Yes, the free account was upgraded to a pro account.
- I asked the person which is responible for managing the account to generate a new key (hopefully without the ":fx" suffix).

Thanks for clarification.

**Comment by daniel-jones-deepl** [comment]
Hi @gszdev, thanks for the confirmation. Okay, in the meantime your workaround explicitly setting `ServerUrl` to https://api.deepl.com/ is a great idea.

**Comment by gszdev** [comment]
Hi @daniel-jones-deepl, generating a new key solved the issue. The new key has no suffix. Thanks for help.
